"""Stable contracts shared by the platform control and execution planes."""

from .models import (
    Artifact,
    ArtifactKind,
    ExecutionPlan,
    Metric,
    RunRequest,
    RunResult,
    RunStage,
    RunStatus,
    StageResult,
)
from .platform import (
    SCHEMA_VERSION,
    ActionProposal,
    ExperimentCandidate,
    ExperimentPlan,
    Event,
    PluginManifest,
    PluginResult,
    RuntimeStatus,
    RepairAction,
    TaskSpec,
    TERMINAL_RUNTIME_STATUSES,
)
from .learning import (
    EvidencePointer,
    LearningContext,
    LearningObservation,
    MechanismEvidence,
    ObjectiveSpec,
    OptimizationStudy,
    OptimizerProposal,
    ParameterSpec,
    Prediction,
    ShadowPolicyProposal,
    TrajectoryStep,
)
from .experiment_graph import (
    ActionKind,
    ActionSpec,
    ExperimentEdge,
    ExperimentNode,
    ExperimentNodeKind,
)
from .rtl_frontend import PortSpec, RTLCandidate, SpecIR, VerificationPackage
from .agent_control import (
    AgentBudget,
    DesignGoal,
    DesignState,
    GoalPreference,
    QoRConstraint,
    READ_ONLY_TOOLS,
    SemanticToolCall,
    ToolName,
    ToolReceipt,
)
from .task_factory import (
    RTL_TO_GDS_CAPABILITY,
    RTLToGDSFactory,
    RTLToGDSRequest,
)
from .protected_evaluation import ProtectedEvaluator
from .l2_optimization import OptimizationRequest, L2HandoffAuthorization
from .product_surface import (
    DEFAULT_PRODUCT_SURFACE, ProductCapabilityRule, ProductRole, ProductSurface,
)

__all__ = [
    "Artifact",
    "ArtifactKind",
    "ExecutionPlan",
    "Metric",
    "RunRequest",
    "RunResult",
    "RunStage",
    "RunStatus",
    "StageResult",
    "SCHEMA_VERSION",
    "ActionProposal",
    "ExperimentCandidate",
    "ExperimentPlan",
    "Event",
    "PluginManifest",
    "PluginResult",
    "RuntimeStatus",
    "RepairAction",
    "TaskSpec",
    "TERMINAL_RUNTIME_STATUSES",
    "EvidencePointer",
    "LearningContext",
    "LearningObservation",
    "MechanismEvidence",
    "ObjectiveSpec",
    "OptimizationStudy",
    "OptimizerProposal",
    "ParameterSpec",
    "Prediction",
    "ShadowPolicyProposal",
    "TrajectoryStep",
    "ActionKind",
    "ActionSpec",
    "ExperimentEdge",
    "ExperimentNode",
    "ExperimentNodeKind",
    "PortSpec",
    "RTLCandidate",
    "SpecIR",
    "VerificationPackage",
    "AgentBudget",
    "DesignGoal",
    "DesignState",
    "GoalPreference",
    "QoRConstraint",
    "READ_ONLY_TOOLS",
    "SemanticToolCall",
    "ToolName",
    "ToolReceipt",
    "RTL_TO_GDS_CAPABILITY",
    "RTLToGDSFactory",
    "RTLToGDSRequest",
    "ProtectedEvaluator",
    "OptimizationRequest", "L2HandoffAuthorization",
    "DEFAULT_PRODUCT_SURFACE", "ProductCapabilityRule", "ProductRole", "ProductSurface",
]
