from __future__ import annotations

"""Install the ``openroad-workbench`` launcher and seed the config.

Usage::

    python3 apps/openroad_workbench/install.py [--bin-dir ~/bin] [--mcp-repo PATH]
"""

import argparse
import os
import stat
import sys
from typing import Optional

# Allow both `python3 apps/openroad_workbench/install.py` and
# `python3 -m openroad_workbench.install`.
if __package__ in (None, ""):
    sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from openroad_workbench.backend import config as config_mod  # noqa: E402

LAUNCHER = """#!/usr/bin/env bash
# OpenROAD Workbench launcher (generated by install.py)
export PYTHONPATH="{apps_dir}${{PYTHONPATH:+:$PYTHONPATH}}"
exec "{python}" -m openroad_workbench.cli "$@"
"""


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(prog="openroad-workbench-install")
    parser.add_argument("--bin-dir", default=os.path.join(os.path.expanduser("~"), "bin"))
    parser.add_argument("--mcp-repo", default=None)
    parser.add_argument("--python", default=sys.executable)
    args = parser.parse_args(argv)

    apps_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    config_mod.ensure_dirs()

    target = os.path.join(os.path.expanduser(args.bin_dir), "openroad-workbench")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as handle:
        handle.write(LAUNCHER.format(apps_dir=apps_dir, python=args.python))
    os.chmod(target, os.stat(target).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    config = config_mod.load_config()
    repo = config_mod.resolve_mcp_repo(args.mcp_repo or config.get("mcp_repo"))
    if repo:
        config["mcp_repo"] = repo
    config_mod.save_config(config)

    print("installed launcher: %s" % target)
    print("python            : %s" % args.python)
    print("apps dir          : %s" % apps_dir)
    print("mcp repo          : %s" % (repo or "(not found — pass --mcp-repo)"))
    print("config            : %s" % config_mod.CONFIG_PATH)
    on_path = any(
        os.path.realpath(part) == os.path.realpath(os.path.dirname(target))
        for part in os.environ.get("PATH", "").split(os.pathsep) if part
    )
    if not on_path:
        print("note              : %s is not on PATH" % os.path.dirname(target))
    return 0


if __name__ == "__main__":
    sys.exit(main())
