#!/usr/bin/env python3
"""Run the two mandatory one-candidate receipts for ORFS-Agent reproduction.

The operator starts this script from the isolated paper-toolchain environment.
It first executes the Adapter natively, then executes the identical immutable
TaskSpec through the platform's ProcessAdapter.  This is deliberately not a
paper-scale claim; it proves only that the full 12-D candidate reaches the
pinned ORFS flow through both required boundaries.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
for item in (ROOT / "packages/contracts/src", ROOT / "packages/execution/src"):
    sys.path.insert(0, str(item))

from openroad_platform_execution import (  # noqa: E402
    ProcessAdapter,
    build_orfs_agent_reproduction_task,
    orfs_agent_reproduction_manifest,
)


DEFAULT_CANDIDATE = {
    "CLK": 4.5, "UTIL": 20, "TNS_End_Percent": 100, "GP_PAD": 0, "DP_PAD": 0,
    "DPO": 1, "PIN_ADJ": 0.4, "UP_ADJ": 0.4, "LB_ADDON": 0.4936,
    "HIER_SYNTH": 0, "CTS_CSIZE": 10, "CTS_CDIA": 80,
}


def _write(path: Path, value: object) -> None:
    path.write_text(json.dumps(value, indent=2, sort_keys=True), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--paper-orfs", type=Path, required=True)
    parser.add_argument("--openroad", type=Path, required=True)
    parser.add_argument("--yosys", type=Path, required=True)
    parser.add_argument("--platform", default="sky130hd", choices=("asap7", "sky130hd"))
    parser.add_argument("--design", default="aes", choices=("aes", "ibex", "jpeg"))
    parser.add_argument("--timeout", type=int, default=10_800)
    parser.add_argument("--candidate-json", type=Path,
                        help="A complete 12-field candidate generated by the pinned upstream algorithm.")
    args = parser.parse_args()
    root = args.output.expanduser().resolve()
    if root.exists() and any(root.iterdir()):
        raise FileExistsError(f"Refusing to overwrite smoke evidence: {root}")
    root.mkdir(parents=True, exist_ok=True)
    candidate = DEFAULT_CANDIDATE
    if args.candidate_json is not None:
        loaded = json.loads(args.candidate_json.expanduser().read_text(encoding="utf-8"))
        if not isinstance(loaded, dict):
            raise ValueError("--candidate-json must contain one complete candidate object")
        candidate = loaded
        _write(root / "upstream_generated_candidate.json", candidate)
    task = build_orfs_agent_reproduction_task(
        project_id="orfs-agent-paper-smoke", design_id=f"{args.platform}-{args.design}",
        design=args.design, platform_name=args.platform, candidate=candidate,
        timeout_seconds=args.timeout, task_id="orfs-agent-paper-smoke-candidate",
    )
    runtime_environment = {key: os.environ[key] for key in ("LD_LIBRARY_PATH", "LIBRARY_PATH", "TCLLIBPATH") if key in os.environ}
    manifest = orfs_agent_reproduction_manifest(
        source=args.source, paper_orfs=args.paper_orfs, openroad_bin=args.openroad,
        yosys_bin=args.yosys, python_executable=ROOT / ".tools/venvs/orfs-agent/bin/python",
        default_timeout_seconds=args.timeout, runtime_environment=runtime_environment,
    )
    _write(root / "task.json", task.to_dict())
    _write(root / "manifest.json", manifest.to_dict())
    # Native: same adapter entry and immutable request, outside ProcessAdapter.
    native = root / "native"; native.mkdir()
    request = native / "adapter_request.json"; result = native / "adapter_result.json"
    _write(request, {"schema_version": 1, "plugin": {"plugin_id": manifest.plugin_id,
           "plugin_version": manifest.plugin_version}, "task": task.to_dict()})
    process = subprocess.run((*manifest.adapter_entry, "--request", str(request), "--result", str(result)),
                             cwd=native, env={**os.environ, **manifest.environment}, text=True,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT, check=False)
    (native / "native_stdout.log").write_text(process.stdout, encoding="utf-8", errors="replace")
    if process.returncode != 0:
        raise RuntimeError(f"native candidate failed; evidence: {native}")
    native_result = json.loads(result.read_text(encoding="utf-8"))
    if native_result.get("status") != "succeeded":
        raise RuntimeError(f"native adapter did not report success: {native_result.get('failure')}")
    # Platform: exact same manifest/task through Runtime's bounded process adapter.
    platform_workspace = root / "platform-process-adapter"
    execution = ProcessAdapter().execute(manifest, task, workspace=platform_workspace)
    _write(root / "smoke_summary.json", {
        "status": "passed" if execution.result.status.value == "succeeded" else "failed",
        "native_result": native_result,
        "platform_result": execution.result.to_dict(),
        "platform_artifacts": list(execution.artifacts),
        "full_candidate": candidate,
        "claim_boundary": "native and ProcessAdapter one-candidate smoke only; no optimization superiority claim",
    })
    if execution.result.status.value != "succeeded":
        raise RuntimeError(f"ProcessAdapter candidate failed; evidence: {platform_workspace}")
    print(root / "smoke_summary.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
